#
# Travis CI Configuration
#

dist: trusty
sudo: false
language: cpp

compiler:
    - clang
    - gcc

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test

        packages:
            - g++-5
            - gcc-5
#           - clang-3.9

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
#   - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.9" CC="clang-3.9"; fi

script:
    - make
    - make test

