#
# Travis CI Configuration
#

sudo: false
language: cpp

compiler:
    - clang
    - gcc

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test

        packages:
            - clang-3.6
            - g++-5
            - gcc-5

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi

script:
    - make
    - make test

